---
dependency:
  name: galaxy
  enabled: false

driver:
  name: docker

platforms:
  - name: ansible-role-php-debian-11
    image: debian:11
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
  - name: ansible-role-php-debian-12
    image: debian:12
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
  - name: ansible-role-php-ubuntu-2204
    image: ubuntu:22.04
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
  - name: ansible-role-php-ubuntu-2404
    image: ubuntu:24.04
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host

provisioner:
  name: ansible

verifier:
  name: testinfra
